### ISSUE TITLE
Readme/Template

### ISSUE THREAD

**Issue by jfallmann** [RickGelhausen/HRIBO#57]
Hi again,

In your config.yaml template under DE for contrasts the help is # comma-seperated list of condition contrasts: treated1_control1,treated2_control2...
but contrasts should be - separated and not _ (which is clear reading the docs however)

The --configfile HRIBO/config.yaml param for running the workflow is obsolete as the path is hardcoded in the Snakefile

**Comment by RickGelhausen** [comment]
Hi,

Thank you for pointing that out and sorry for the inconveniences this caused.

I updated the documentation accordingly
